---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
   - name: delete wireshark
    apt:
      name: wireshark-qt
      state: absent
      autoremove: yes
      purge: yes
      autoclean: yes
