all:
  hosts:
    nfs01:
      ansible_host: 172.31.39.232
    web01:
      ansible_host: 172.31.39.10
    web02:
      ansible_host: 172.31.39.99
    db01:
      ansible_host: 172.31.37.66 ansible_ssh_user=ubuntu
  
  children:
    webservers:
      hosts:
        web01:
        web02:
        web03:
    dbservers:
      hosts:
        db01:
    storage:
      hosts:
        nfs01:

    vars:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: stockholm_key.pem

