all:
  hosts:
    web01:
      ansible_host: 172.31.27.65
      ansible_user: ec2-user
    web02:
      ansible_host: 172.31.36.61 
      ansible_user: ec2-user
  
  children:
    uat_webservers:
      hosts:
        web01:
        web02:
     
    vars:
      ansible_user: ec2-user
      ansible_ssh_private_key_file: stockholm_key.pem

