---
- name: install apache
  become: true
  tasks:
    yum: "httpd"
    state: present

- name: install git
  become: true
  task:
    yum: "git"
    state: present

- name: clone a repo
  become: true
  git:
    repo: https://github.com/seyi007i/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  become: true
  service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  file:
    path: /var/www/html/html
    state: absent
